// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4OiaGhzr8bxvdsuZjZd2kYmj-5V9bTK4',
    appId: '1:311888649321:web:fb3e74502593e2af3bd6f8',
    messagingSenderId: '311888649321',
    projectId: 'demensiaapp',
    authDomain: 'demensiaapp.firebaseapp.com',
    storageBucket: 'demensiaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsTTC1CpCTj0VvvjNJfFisCd0MpKuV93U',
    appId: '1:311888649321:android:05abbdec6c6e577d3bd6f8',
    messagingSenderId: '311888649321',
    projectId: 'demensiaapp',
    storageBucket: 'demensiaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV0DXovlhm1xGVMxxYmDxMe9syJ0ndh54',
    appId: '1:311888649321:ios:b33ab98458a9accb3bd6f8',
    messagingSenderId: '311888649321',
    projectId: 'demensiaapp',
    storageBucket: 'demensiaapp.appspot.com',
    iosBundleId: 'com.example.demensiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV0DXovlhm1xGVMxxYmDxMe9syJ0ndh54',
    appId: '1:311888649321:ios:b33ab98458a9accb3bd6f8',
    messagingSenderId: '311888649321',
    projectId: 'demensiaapp',
    storageBucket: 'demensiaapp.appspot.com',
    iosBundleId: 'com.example.demensiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4OiaGhzr8bxvdsuZjZd2kYmj-5V9bTK4',
    appId: '1:311888649321:web:46bf46d39834b4d93bd6f8',
    messagingSenderId: '311888649321',
    projectId: 'demensiaapp',
    authDomain: 'demensiaapp.firebaseapp.com',
    storageBucket: 'demensiaapp.appspot.com',
  );

}